#!/bin/sh


# Copyright 2024 Montana State University Software Engineering and Cybersecurity Laboratory
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the “Software”),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

########################################################################
# Prepares Environment For PIQUE-Cloud and runs PIQUE on sample targets
########################################################################

WORKDIR="$PWD"
INPUT_MESSAGE="##############################################\n#   INPUT NEEDED    \n##############################################"
PROGNAME="

               ██████╗ ██╗ ██████╗ ██╗   ██╗███████╗
               ██╔══██╗██║██╔═══██╗██║   ██║██╔════╝
               ██████╔╝██║██║   ██║██║   ██║█████╗
               ██╔═══╝ ██║██║▄▄ ██║██║   ██║██╔══╝
               ██║     ██║╚██████╔╝╚██████╔╝███████╗
               ╚═╝     ╚═╝ ╚══▀▀═╝  ╚═════╝ ╚══════╝

                     ██████╗██╗      ██████╗ ██╗   ██╗██████╗
                    ██╔════╝██║     ██╔═══██╗██║   ██║██╔══██╗
                    ██║     ██║     ██║   ██║██║   ██║██║  ██║
                    ██║     ██║     ██║   ██║██║   ██║██║  ██║
                    ╚██████╗███████╗╚██████╔╝╚██████╔╝██████╔╝
                     ╚═════╝╚══════╝ ╚═════╝  ╚═════╝ ╚═════╝

 ------------------------------------------------------------------------

"
printBanner() {
    COLUMNS=$(tput cols)
    # shellcheck disable=SC2002
    if [ -f msu_logo_ascii.txt ] && [ -x /bin/perl ] && [ "$COLUMNS" -gt 100 ]; then
      cat msu_logo_ascii.txt | perl -pe 'select undef,undef,undef,.01555'
      printf "$PROGNAME" | perl -pe 'select undef,undef,undef,.01555'
      echo " " | perl -pe 'select undef,undef,undef,0.20000'
    else
        printf "$PROGNAME"
    fi
}

# Dependency Checks
check_deps() {
    # Check that wget is installed
    printf "Checking dependencies...\n"
    [ -x "$(which wget)" ] || { printf "\u001b[31mERROR: wget is not installed. Please install wget on your system or perform manual installation of PIQUE-Cloud\nexit 1\n\u001b[0m"; exit 1; }
    printf "\twget is installed\n"

    # Check that docker is installed and user is logged in
    [ -x "$(which docker)" ] || { printf "\u001b[31mPlease ensure that docker is installed, running, and configured with your username and login.\u001b[0m\nexit 1\n"; exit 1; }
    printf "\tdocker is installed\n"

    # Check git is installed
    git --version >/dev/null 2>&1 || { printf "\u001b[31mgit is not installed. Please install git on your system to continue PIQUE-Cloud setup\u001b[0m\nexit 1\n"; exit 1; }
    printf "\tgit is installed\n"
    printf "\u001b[32mDependency check completed successfully\n\n\u001b[0m"
}

# Check for/create input, output, and subdirectories
set_up_directories() {
    printf "Checking directory structure...\n"
    [ -d "$WORKDIR/input/" ] || { mkdir -p "$WORKDIR/input/"; }
    [ -d "$WORKDIR/output/" ] || { mkdir -p "$WORKDIR/output/"; }
    printf "\u001b[32mDirectory check/setup complete\n\n\u001b[0m"
}

# Grabs the sample target file from msusel-pique-cloud-dockerfile github repo
generate_sample_target() {
    printf "Checking if target file exists...\n"
    WGET_OPTS="-O $WORKDIR/input/docker-image-target.json"
    TARGET="https://raw.githubusercontent.com/MSUSEL/msusel-pique-cloud-dockerfile/master/input/docker-image-target.json"

    [ -f "$WORKDIR/input/docker-image-target.json" ] || { printf "Getting a sample target file from PIQUE-Cloud\n"; \
        wget $WGET_OPTS $TARGET; \
        printf "\u001b[32mSample target file created\u001b[0m\n"; }
    printf "\u001b[32mTarget file configured\u001b[0m\n\n"
}

run() {
    printBanner
    check_deps
    set_up_directories
    generate_sample_target

    docker run -it --rm -v "/var/run/docker.sock:/var/run/docker.sock:rw" -v "$WORKDIR"/input:/input -v "$WORKDIR"/output:/output msusel/pique-cloud-dockerfile:latest
}
run

